package com.adsum.camel_masterapplication.Config

object CamelConfig {

    var WEBURL = "https://uaqcrc.com/wp-json/camel/v1/"
    var getSchedulImage = "get_race_scheduling"
    var racelistArchiveMonthYear="racelistArchiveMonthYear"
    var Year_list="archiveMonthYear"
    val get_term_condition_details="get_term_and_condition_detail"
    var get_notification = "get_notification"
    val logout="logout"
    val viewuser="viewuser"
    val LogOut="logout?user_id="
    val userList="viewuser"
    val login="auth?username={username}&password={password}"
    val racelist= "get_race_detail"
    val subracelist="race_view_detail?raceid="
    val updateRaceSchedule="race_date"
    val removeRaceList="rmvracedetail?race_id"
    var selectedUserList="add_participant_in_race?race_id="
    val profileupdate="updateProfileDetails"
    val profile="getProfileDetails?user_id="
    val profileimage="updateProfilePicture"
    val malelist="viewCamel?user_id="
    var removeCamel="delCamel?id="
    val getcamelcategory = "getcategory"
    var addUser = "adduser"
    var blockUser="block_user"
    val participateinrace = "participate_in_Race"
    val ViewRoundMemberlisting = "viewRoundMemberlisting"
    var removecamel="removeRoundMemberOption?rl_id="
    val addCamelMember = "addRoundMemberOption?race_id={race_id}&round_id={round_id}&user_id={user_id}&camel_id={camel_id}"
    var participate_in_Raceround = "participate_in_Raceround"
    var rmvRaceSchedule = "rmv_race_scheduling"
    var addRaceSchedule = "add_race_scheduling"
    var updateadminRaceSchedule = "upd_race_scheduling"
    val addcamel = "addCamel?camel={camel}&gender={gender}&status={status}&user_id={user_id}"
    var spinnerCategory = "getcategory"
    var addRaceDetail = "addracedetail"
    var updateNotification = "update_notification"
    val listofuser="list_of_user"
    var change_subscrition_status="change_subscrition_status"
}